routes:
  - host: nodejs-app.local
    service:
      name: nodejs-app
      port: 3000
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
  - host: krakend.local
    service:
      name: krakend
      port: 8080
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /